export const MACROS = [
  "Title",
  "Group",
  "Customer",
  "Owner",
  "State",
  "Pending till",
  "Priority",
  "Tags",
  "Note",
  ""
]

export const SLA = [
  "State",
  "Title",
  "Organization",
  "Type",
  "Group",
  "Customer",
  "Owner",
  "Pending till",
  "Priority",
  "Tags",
  "Note",
  "Escalation at",
  "Escalation at (First Response Time)",
  "Escalation at (Update Time)",
  "Escalation at (Close Time)",
  "Last Contact",
  "Last Contact (Agent)",
  "Last Contact (Customer)",
  "First Response",
  "Closing Time",
  "Created by",
  "Created at",
  "Update by",
  "Update at",
  "Subscript",
  "Type",
  "Visibility",
  "To",
  "CC",
  "Text",
  "From",
  "Subject",
  "Sender",
  "Created By",
  "Origin by",
  "First Name",
  "Last Name",
  "Login",
  "Email",
  "Web",
  "Phone",
  ""
]

const tags = ["contains one", "contains all", "contains all not", "contains all"]
const options = [
  "before (absolute)",
  "after (absolute)",
  "before (relative)",
  "after (relative)",
  "within next (relative)",
  "within last (relative)",
  "till (relative)",
  "from (relative)"
]
